/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef ABSYN_HEADER
#define ABSYN_HEADER

/* strdup was not in the ISO C standard before 6/2019 (C2x), but in POSIX 1003.1.
 * See: https://en.cppreference.com/w/c/experimental/dynamic/strdup
 * Setting _POSIX_C_SOURCE to 200809L activates strdup in string.h.
 */
#define _POSIX_C_SOURCE 200809L

#include <stddef.h> /* NULL */
#include <string.h> /* strdup */

/* C++ Abstract Syntax Interface.*/

/********************   TypeDef Section    ********************/

typedef int    Integer;
typedef char   Char;
typedef double Double;
typedef char  *String;
typedef char  *Ident;
typedef char  *IntLit;
typedef char  *FloatLit;
typedef char  *StrLit;
typedef char  *PreprocLine;
typedef char  *LineEol;

/********************   Forward Declarations    ***********************/
struct Program_;
typedef struct Program_ *Program;

struct LeadingEols_;
typedef struct LeadingEols_ *LeadingEols;

struct TopDecls_;
typedef struct TopDecls_ *TopDecls;

struct TopDecl_;
typedef struct TopDecl_ *TopDecl;

struct Defs_;
typedef struct Defs_ *Defs;

struct PreprocDecl_;
typedef struct PreprocDecl_ *PreprocDecl;

struct ParamListOpt_;
typedef struct ParamListOpt_ *ParamListOpt;

struct ParamListTail_;
typedef struct ParamListTail_ *ParamListTail;

struct Stmt_;
typedef struct Stmt_ *Stmt;

struct ReturnExprOpt_;
typedef struct ReturnExprOpt_ *ReturnExprOpt;

struct StmtList_;
typedef struct StmtList_ *StmtList;

struct StmtListNonEmpty_;
typedef struct StmtListNonEmpty_ *StmtListNonEmpty;

struct ElseIfList_;
typedef struct ElseIfList_ *ElseIfList;

struct ElseIf_;
typedef struct ElseIf_ *ElseIf;

struct ElseOpt_;
typedef struct ElseOpt_ *ElseOpt;

struct IfCond_;
typedef struct IfCond_ *IfCond;

struct EndIf_;
typedef struct EndIf_ *EndIf;

struct EndIfOpt_;
typedef struct EndIfOpt_ *EndIfOpt;

struct DoOpt_;
typedef struct DoOpt_ *DoOpt;

struct WhileCond_;
typedef struct WhileCond_ *WhileCond;

struct EndDo_;
typedef struct EndDo_ *EndDo;

struct EndDoOpt_;
typedef struct EndDoOpt_ *EndDoOpt;

struct EndCase_;
typedef struct EndCase_ *EndCase;

struct EndCaseOpt_;
typedef struct EndCaseOpt_ *EndCaseOpt;

struct StepOpt_;
typedef struct StepOpt_ *StepOpt;

struct EndFor_;
typedef struct EndFor_ *EndFor;

struct EndForOpt_;
typedef struct EndForOpt_ *EndForOpt;

struct ForEachVars_;
typedef struct ForEachVars_ *ForEachVars;

struct ForEachVarsTail_;
typedef struct ForEachVarsTail_ *ForEachVarsTail;

struct ForEachExprs_;
typedef struct ForEachExprs_ *ForEachExprs;

struct ForEachExprsTail_;
typedef struct ForEachExprsTail_ *ForEachExprsTail;

struct ForEachDescOpt_;
typedef struct ForEachDescOpt_ *ForEachDescOpt;

struct CaseList_;
typedef struct CaseList_ *CaseList;

struct CaseClause_;
typedef struct CaseClause_ *CaseClause;

struct CaseCondList_;
typedef struct CaseCondList_ *CaseCondList;

struct CaseCondClause_;
typedef struct CaseCondClause_ *CaseCondClause;

struct OtherwiseOpt_;
typedef struct OtherwiseOpt_ *OtherwiseOpt;

struct BreakExprOpt_;
typedef struct BreakExprOpt_ *BreakExprOpt;

struct RecoverOpt_;
typedef struct RecoverOpt_ *RecoverOpt;

struct RecoverUsingOpt_;
typedef struct RecoverUsingOpt_ *RecoverUsingOpt;

struct EndSequence_;
typedef struct EndSequence_ *EndSequence;

struct EndSequenceOpt_;
typedef struct EndSequenceOpt_ *EndSequenceOpt;

struct SwitchCond_;
typedef struct SwitchCond_ *SwitchCond;

struct EndSwitch_;
typedef struct EndSwitch_ *EndSwitch;

struct EndSwitchOpt_;
typedef struct EndSwitchOpt_ *EndSwitchOpt;

struct EndStruct_;
typedef struct EndStruct_ *EndStruct;

struct EndStructOpt_;
typedef struct EndStructOpt_ *EndStructOpt;

struct EndClass_;
typedef struct EndClass_ *EndClass;

struct EndClassOpt_;
typedef struct EndClassOpt_ *EndClassOpt;

struct EndEnum_;
typedef struct EndEnum_ *EndEnum;

struct EndEnumOpt_;
typedef struct EndEnumOpt_ *EndEnumOpt;

struct CaseValue_;
typedef struct CaseValue_ *CaseValue;

struct StmtEnd_;
typedef struct StmtEnd_ *StmtEnd;

struct EnumDecl_;
typedef struct EnumDecl_ *EnumDecl;

struct EnumListOpt_;
typedef struct EnumListOpt_ *EnumListOpt;

struct EnumListTail_;
typedef struct EnumListTail_ *EnumListTail;

struct EnumSep_;
typedef struct EnumSep_ *EnumSep;

struct EnumItem_;
typedef struct EnumItem_ *EnumItem;

struct EnumValueOpt_;
typedef struct EnumValueOpt_ *EnumValueOpt;

struct LineEolOpt_;
typedef struct LineEolOpt_ *LineEolOpt;

struct StructDecl_;
typedef struct StructDecl_ *StructDecl;

struct StructBody_;
typedef struct StructBody_ *StructBody;

struct StructMember_;
typedef struct StructMember_ *StructMember;

struct FieldInitList_;
typedef struct FieldInitList_ *FieldInitList;

struct FieldInit_;
typedef struct FieldInit_ *FieldInit;

struct StaticDecl_;
typedef struct StaticDecl_ *StaticDecl;

struct ClassDecl_;
typedef struct ClassDecl_ *ClassDecl;

struct CreateOpt_;
typedef struct CreateOpt_ *CreateOpt;

struct ClassName_;
typedef struct ClassName_ *ClassName;

struct InheritOpt_;
typedef struct InheritOpt_ *InheritOpt;

struct InheritKeyword_;
typedef struct InheritKeyword_ *InheritKeyword;

struct StaticClassOpt_;
typedef struct StaticClassOpt_ *StaticClassOpt;

struct ClassBody_;
typedef struct ClassBody_ *ClassBody;

struct ClassMember_;
typedef struct ClassMember_ *ClassMember;

struct VisibilityScope_;
typedef struct VisibilityScope_ *VisibilityScope;

struct VarList_;
typedef struct VarList_ *VarList;

struct VarDecl_;
typedef struct VarDecl_ *VarDecl;

struct VarInitOpt_;
typedef struct VarInitOpt_ *VarInitOpt;

struct MethodParamsOpt_;
typedef struct MethodParamsOpt_ *MethodParamsOpt;

struct Expr_;
typedef struct Expr_ *Expr;

struct ExprOr_;
typedef struct ExprOr_ *ExprOr;

struct CallExpr_;
typedef struct CallExpr_ *CallExpr;

struct ArgListOpt_;
typedef struct ArgListOpt_ *ArgListOpt;

struct ArgListTail_;
typedef struct ArgListTail_ *ArgListTail;

struct ExprListOpt_;
typedef struct ExprListOpt_ *ExprListOpt;

struct ExprListTail_;
typedef struct ExprListTail_ *ExprListTail;

struct QualifiedId_;
typedef struct QualifiedId_ *QualifiedId;

struct LHS_;
typedef struct LHS_ *LHS;

struct LValue_;
typedef struct LValue_ *LValue;

struct SubscriptList_;
typedef struct SubscriptList_ *SubscriptList;

struct SubscriptListTail_;
typedef struct SubscriptListTail_ *SubscriptListTail;

struct Literal_;
typedef struct Literal_ *Literal;

struct Napis_;
typedef struct Napis_ *Napis;

struct Def_;
typedef struct Def_ *Def;

struct FunctionDef_;
typedef struct FunctionDef_ *FunctionDef;

struct ProcedureDef_;
typedef struct ProcedureDef_ *ProcedureDef;

struct StaticOpt_;
typedef struct StaticOpt_ *StaticOpt;

struct LocalDeclsOpt_;
typedef struct LocalDeclsOpt_ *LocalDeclsOpt;

struct LocalDecl_;
typedef struct LocalDecl_ *LocalDecl;

struct StaticDeclsOpt_;
typedef struct StaticDeclsOpt_ *StaticDeclsOpt;

struct StaticItemList_;
typedef struct StaticItemList_ *StaticItemList;

struct StaticItemTail_;
typedef struct StaticItemTail_ *StaticItemTail;

struct StaticItem_;
typedef struct StaticItem_ *StaticItem;

struct StaticArrayDimsOpt_;
typedef struct StaticArrayDimsOpt_ *StaticArrayDimsOpt;

struct StaticInitOpt_;
typedef struct StaticInitOpt_ *StaticInitOpt;

struct IdentInitList_;
typedef struct IdentInitList_ *IdentInitList;

struct IdentInitTail_;
typedef struct IdentInitTail_ *IdentInitTail;

struct IdentInit_;
typedef struct IdentInit_ *IdentInit;

struct InitOpt_;
typedef struct InitOpt_ *InitOpt;

struct MethodDef_;
typedef struct MethodDef_ *MethodDef;

/********************   Abstract Syntax Classes    ********************/

struct Program_
{
   enum
   {
      is_ProgramRoot
   } kind;
   union
   {
      struct
      {
         Defs        defs_;
         LeadingEols leadingeols_;
         TopDecls    topdecls_;
      } programRoot_;
   } u;
};

Program make_ProgramRoot( LeadingEols p0, TopDecls p1, Defs p2 );

struct LeadingEols_
{
   enum
   {
      is_LeadingEolsEmpty
   } kind;
   union
   {
   } u;
};

LeadingEols make_LeadingEolsEmpty( void );

struct TopDecls_
{
   enum
   {
      is_ListTopDeclEmpty,
      is_ListTopDeclCons,
      is_ListTopDeclLine
   } kind;
   union
   {
      struct
      {
         TopDecl  topdecl_;
         TopDecls topdecls_;
      } listTopDeclCons_;
      struct
      {
         LineEol  lineeol_;
         TopDecls topdecls_;
      } listTopDeclLine_;
   } u;
};

TopDecls make_ListTopDeclEmpty( void );
TopDecls make_ListTopDeclCons( TopDecl p0, TopDecls p1 );
TopDecls make_ListTopDeclLine( LineEol p0, TopDecls p1 );

struct TopDecl_
{
   enum
   {
      is_TopDeclEnum,
      is_TopDeclClass,
      is_TopDeclStruct,
      is_TopDeclPreproc,
      is_TopDeclStatic
   } kind;
   union
   {
      struct
      {
         EnumDecl enumdecl_;
      } topDeclEnum_;
      struct
      {
         ClassDecl classdecl_;
      } topDeclClass_;
      struct
      {
         StructDecl structdecl_;
      } topDeclStruct_;
      struct
      {
         PreprocDecl preprocdecl_;
      } topDeclPreproc_;
      struct
      {
         StaticDecl staticdecl_;
      } topDeclStatic_;
   } u;
};

TopDecl make_TopDeclEnum( EnumDecl p0 );
TopDecl make_TopDeclClass( ClassDecl p0 );
TopDecl make_TopDeclStruct( StructDecl p0 );
TopDecl make_TopDeclPreproc( PreprocDecl p0 );
TopDecl make_TopDeclStatic( StaticDecl p0 );

struct Defs_
{
   enum
   {
      is_ListDefSingle,
      is_ListDefCons
   } kind;
   union
   {
      struct
      {
         Def def_;
      } listDefSingle_;
      struct
      {
         Def  def_;
         Defs defs_;
      } listDefCons_;
   } u;
};

Defs make_ListDefSingle( Def p0 );
Defs make_ListDefCons( Def p0, Defs p1 );

struct PreprocDecl_
{
   enum
   {
      is_PreprocDeclLine
   } kind;
   union
   {
      struct
      {
         PreprocLine preprocline_;
         StmtEnd     stmtend_;
      } preprocDeclLine_;
   } u;
};

PreprocDecl make_PreprocDeclLine( PreprocLine p0, StmtEnd p1 );

struct ParamListOpt_
{
   enum
   {
      is_OptParamListEmpty,
      is_OptParamListSome
   } kind;
   union
   {
      struct
      {
         Ident         ident_;
         ParamListTail paramlisttail_;
      } optParamListSome_;
   } u;
};

ParamListOpt make_OptParamListEmpty( void );
ParamListOpt make_OptParamListSome( Ident p0, ParamListTail p1 );

struct ParamListTail_
{
   enum
   {
      is_ListParamTailEmpty,
      is_ListParamTailCons
   } kind;
   union
   {
      struct
      {
         Ident         ident_;
         ParamListTail paramlisttail_;
      } listParamTailCons_;
   } u;
};

ParamListTail make_ListParamTailEmpty( void );
ParamListTail make_ListParamTailCons( Ident p0, ParamListTail p1 );

struct Stmt_
{
   enum
   {
      is_StmtAssignInl,
      is_StmtAssignAdd,
      is_StmtAssignSub,
      is_StmtAssignMul,
      is_StmtAssignDiv,
      is_StmtAssignMod,
      is_StmtAssignPow,
      is_StmtAssignPow2,
      is_StmtCall,
      is_StmtIf,
      is_StmtDoWhile,
      is_StmtFor,
      is_StmtForEach,
      is_StmtSwitch,
      is_StmtDoCase,
      is_StmtSequence,
      is_StmtBreak,
      is_StmtExit,
      is_StmtLoop,
      is_StmtReturn,
      is_StmtStructDecl
   } kind;
   union
   {
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignInl_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignAdd_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignSub_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignMul_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignDiv_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignMod_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignPow_;
      struct
      {
         Expr    expr_;
         LHS     lhs_;
         StmtEnd stmtend_;
      } stmtAssignPow2_;
      struct
      {
         CallExpr callexpr_;
         StmtEnd  stmtend_;
      } stmtCall_;
      struct
      {
         ElseIfList elseiflist_;
         ElseOpt    elseopt_;
         EndIf      endif_;
         IfCond     ifcond_;
         LineEol    lineeol_;
         StmtEnd    stmtend_;
         StmtList   stmtlist_;
      } stmtIf_;
      struct
      {
         DoOpt     doopt_;
         EndDo     enddo_;
         LineEol   lineeol_;
         StmtEnd   stmtend_;
         StmtList  stmtlist_;
         WhileCond whilecond_;
      } stmtDoWhile_;
      struct
      {
         EndFor   endfor_;
         Expr     expr_1, expr_2;
         Ident    ident_;
         LineEol  lineeol_;
         StepOpt  stepopt_;
         StmtEnd  stmtend_;
         StmtList stmtlist_;
      } stmtFor_;
      struct
      {
         EndFor         endfor_;
         ForEachDescOpt foreachdescopt_;
         ForEachExprs   foreachexprs_;
         ForEachVars    foreachvars_;
         LineEol        lineeol_;
         StmtEnd        stmtend_;
         StmtList       stmtlist_;
      } stmtForEach_;
      struct
      {
         CaseList     caselist_;
         EndSwitch    endswitch_;
         LineEol      lineeol_;
         OtherwiseOpt otherwiseopt_;
         StmtEnd      stmtend_;
         SwitchCond   switchcond_;
      } stmtSwitch_;
      struct
      {
         CaseCondList casecondlist_;
         EndCase      endcase_;
         LineEol      lineeol_;
         OtherwiseOpt otherwiseopt_;
         StmtEnd      stmtend_;
      } stmtDoCase_;
      struct
      {
         EndSequence endsequence_;
         LineEol     lineeol_;
         RecoverOpt  recoveropt_;
         StmtEnd     stmtend_;
         StmtList    stmtlist_;
      } stmtSequence_;
      struct
      {
         BreakExprOpt breakexpropt_;
         StmtEnd      stmtend_;
      } stmtBreak_;
      struct
      {
         StmtEnd stmtend_;
      } stmtExit_;
      struct
      {
         StmtEnd stmtend_;
      } stmtLoop_;
      struct
      {
         ReturnExprOpt returnexpropt_;
         StmtEnd       stmtend_;
      } stmtReturn_;
      struct
      {
         StructDecl structdecl_;
      } stmtStructDecl_;
   } u;
};

Stmt make_StmtAssignInl( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignAdd( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignSub( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignMul( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignDiv( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignMod( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignPow( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtAssignPow2( LHS p0, Expr p1, StmtEnd p2 );
Stmt make_StmtCall( CallExpr p0, StmtEnd p1 );
Stmt make_StmtIf( IfCond p0, LineEol p1, StmtList p2, ElseIfList p3, ElseOpt p4, EndIf p5, StmtEnd p6 );
Stmt make_StmtDoWhile( DoOpt p0, WhileCond p1, LineEol p2, StmtList p3, EndDo p4, StmtEnd p5 );
Stmt make_StmtFor( Ident p0, Expr p1, Expr p2, StepOpt p3, LineEol p4, StmtList p5, EndFor p6, StmtEnd p7 );
Stmt make_StmtForEach( ForEachVars p0, ForEachExprs p1, ForEachDescOpt p2, LineEol p3, StmtList p4, EndFor p5,
                       StmtEnd p6 );
Stmt make_StmtSwitch( SwitchCond p0, LineEol p1, CaseList p2, OtherwiseOpt p3, EndSwitch p4, StmtEnd p5 );
Stmt make_StmtDoCase( LineEol p0, CaseCondList p1, OtherwiseOpt p2, EndCase p3, StmtEnd p4 );
Stmt make_StmtSequence( LineEol p0, StmtList p1, RecoverOpt p2, EndSequence p3, StmtEnd p4 );
Stmt make_StmtBreak( BreakExprOpt p0, StmtEnd p1 );
Stmt make_StmtExit( StmtEnd p0 );
Stmt make_StmtLoop( StmtEnd p0 );
Stmt make_StmtReturn( ReturnExprOpt p0, StmtEnd p1 );
Stmt make_StmtStructDecl( StructDecl p0 );

struct ReturnExprOpt_
{
   enum
   {
      is_ReturnExprOptEmpty,
      is_ReturnExprOptSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } returnExprOptSome_;
   } u;
};

ReturnExprOpt make_ReturnExprOptEmpty( void );
ReturnExprOpt make_ReturnExprOptSome( Expr p0 );

struct StmtList_
{
   enum
   {
      is_ListStmtEmpty,
      is_ListStmtCons,
      is_ListStmtLine
   } kind;
   union
   {
      struct
      {
         Stmt     stmt_;
         StmtList stmtlist_;
      } listStmtCons_;
      struct
      {
         LineEol  lineeol_;
         StmtList stmtlist_;
      } listStmtLine_;
   } u;
};

StmtList make_ListStmtEmpty( void );
StmtList make_ListStmtCons( Stmt p0, StmtList p1 );
StmtList make_ListStmtLine( LineEol p0, StmtList p1 );

struct StmtListNonEmpty_
{
   enum
   {
      is_ListStmtNonEmpty
   } kind;
   union
   {
      struct
      {
         Stmt     stmt_;
         StmtList stmtlist_;
      } listStmtNonEmpty_;
   } u;
};

StmtListNonEmpty make_ListStmtNonEmpty( Stmt p0, StmtList p1 );

struct ElseIfList_
{
   enum
   {
      is_ListElseIfEmpty,
      is_ListElseIfCons
   } kind;
   union
   {
      struct
      {
         ElseIf     elseif_;
         ElseIfList elseiflist_;
      } listElseIfCons_;
   } u;
};

ElseIfList make_ListElseIfEmpty( void );
ElseIfList make_ListElseIfCons( ElseIf p0, ElseIfList p1 );

struct ElseIf_
{
   enum
   {
      is_ElseIfClause
   } kind;
   union
   {
      struct
      {
         IfCond   ifcond_;
         LineEol  lineeol_;
         StmtList stmtlist_;
      } elseIfClause_;
   } u;
};

ElseIf make_ElseIfClause( IfCond p0, LineEol p1, StmtList p2 );

struct ElseOpt_
{
   enum
   {
      is_OptElseEmpty,
      is_OptElseSome
   } kind;
   union
   {
      struct
      {
         LineEol  lineeol_;
         StmtList stmtlist_;
      } optElseSome_;
   } u;
};

ElseOpt make_OptElseEmpty( void );
ElseOpt make_OptElseSome( LineEol p0, StmtList p1 );

struct IfCond_
{
   enum
   {
      is_IfCondExpr
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } ifCondExpr_;
   } u;
};

IfCond make_IfCondExpr( Expr p0 );

struct EndIf_
{
   enum
   {
      is_EndIfWord,
      is_EndIfClause
   } kind;
   union
   {
      struct
      {
         EndIfOpt endifopt_;
      } endIfClause_;
   } u;
};

EndIf make_EndIfWord( void );
EndIf make_EndIfClause( EndIfOpt p0 );

struct EndIfOpt_
{
   enum
   {
      is_EndIfOptEmpty,
      is_EndIfOptIf
   } kind;
   union
   {
   } u;
};

EndIfOpt make_EndIfOptEmpty( void );
EndIfOpt make_EndIfOptIf( void );

struct DoOpt_
{
   enum
   {
      is_DoOptEmpty,
      is_DoOptDo
   } kind;
   union
   {
   } u;
};

DoOpt make_DoOptEmpty( void );
DoOpt make_DoOptDo( void );

struct WhileCond_
{
   enum
   {
      is_WhileCondExpr
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } whileCondExpr_;
   } u;
};

WhileCond make_WhileCondExpr( Expr p0 );

struct EndDo_
{
   enum
   {
      is_EndDoWord,
      is_EndWhileWord,
      is_EndDoClause
   } kind;
   union
   {
      struct
      {
         EndDoOpt enddoopt_;
      } endDoClause_;
   } u;
};

EndDo make_EndDoWord( void );
EndDo make_EndWhileWord( void );
EndDo make_EndDoClause( EndDoOpt p0 );

struct EndDoOpt_
{
   enum
   {
      is_EndDoOptEmpty,
      is_EndDoOptDo,
      is_EndDoOptWhile
   } kind;
   union
   {
   } u;
};

EndDoOpt make_EndDoOptEmpty( void );
EndDoOpt make_EndDoOptDo( void );
EndDoOpt make_EndDoOptWhile( void );

struct EndCase_
{
   enum
   {
      is_EndCaseWord,
      is_EndCaseClause
   } kind;
   union
   {
      struct
      {
         EndCaseOpt endcaseopt_;
      } endCaseClause_;
   } u;
};

EndCase make_EndCaseWord( void );
EndCase make_EndCaseClause( EndCaseOpt p0 );

struct EndCaseOpt_
{
   enum
   {
      is_EndCaseOptEmpty,
      is_EndCaseOptCase
   } kind;
   union
   {
   } u;
};

EndCaseOpt make_EndCaseOptEmpty( void );
EndCaseOpt make_EndCaseOptCase( void );

struct StepOpt_
{
   enum
   {
      is_OptStepEmpty,
      is_OptStepSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } optStepSome_;
   } u;
};

StepOpt make_OptStepEmpty( void );
StepOpt make_OptStepSome( Expr p0 );

struct EndFor_
{
   enum
   {
      is_EndForWord,
      is_EndForClause
   } kind;
   union
   {
      struct
      {
         EndForOpt endforopt_;
      } endForClause_;
   } u;
};

EndFor make_EndForWord( void );
EndFor make_EndForClause( EndForOpt p0 );

struct EndForOpt_
{
   enum
   {
      is_EndForOptEmpty,
      is_EndForOptFor
   } kind;
   union
   {
   } u;
};

EndForOpt make_EndForOptEmpty( void );
EndForOpt make_EndForOptFor( void );

struct ForEachVars_
{
   enum
   {
      is_ForEachVarsMain
   } kind;
   union
   {
      struct
      {
         ForEachVarsTail foreachvarstail_;
         Ident           ident_;
      } forEachVarsMain_;
   } u;
};

ForEachVars make_ForEachVarsMain( Ident p0, ForEachVarsTail p1 );

struct ForEachVarsTail_
{
   enum
   {
      is_ListForEachVarsTailEmpty,
      is_ListForEachVarsTailCons
   } kind;
   union
   {
      struct
      {
         ForEachVarsTail foreachvarstail_;
         Ident           ident_;
      } listForEachVarsTailCons_;
   } u;
};

ForEachVarsTail make_ListForEachVarsTailEmpty( void );
ForEachVarsTail make_ListForEachVarsTailCons( Ident p0, ForEachVarsTail p1 );

struct ForEachExprs_
{
   enum
   {
      is_ForEachExprsMain
   } kind;
   union
   {
      struct
      {
         Expr             expr_;
         ForEachExprsTail foreachexprstail_;
      } forEachExprsMain_;
   } u;
};

ForEachExprs make_ForEachExprsMain( Expr p0, ForEachExprsTail p1 );

struct ForEachExprsTail_
{
   enum
   {
      is_ListForEachExprsTailEmpty,
      is_ListForEachExprsTailCons
   } kind;
   union
   {
      struct
      {
         Expr             expr_;
         ForEachExprsTail foreachexprstail_;
      } listForEachExprsTailCons_;
   } u;
};

ForEachExprsTail make_ListForEachExprsTailEmpty( void );
ForEachExprsTail make_ListForEachExprsTailCons( Expr p0, ForEachExprsTail p1 );

struct ForEachDescOpt_
{
   enum
   {
      is_ForEachDescOptEmpty,
      is_ForEachDescOptSome
   } kind;
   union
   {
   } u;
};

ForEachDescOpt make_ForEachDescOptEmpty( void );
ForEachDescOpt make_ForEachDescOptSome( void );

struct CaseList_
{
   enum
   {
      is_ListCaseEmpty,
      is_ListCaseCons
   } kind;
   union
   {
      struct
      {
         CaseClause caseclause_;
         CaseList   caselist_;
      } listCaseCons_;
   } u;
};

CaseList make_ListCaseEmpty( void );
CaseList make_ListCaseCons( CaseClause p0, CaseList p1 );

struct CaseClause_
{
   enum
   {
      is_CaseClauseItem
   } kind;
   union
   {
      struct
      {
         CaseValue casevalue_;
         LineEol   lineeol_;
         StmtList  stmtlist_;
      } caseClauseItem_;
   } u;
};

CaseClause make_CaseClauseItem( CaseValue p0, LineEol p1, StmtList p2 );

struct CaseCondList_
{
   enum
   {
      is_ListCaseCondEmpty,
      is_ListCaseCondCons
   } kind;
   union
   {
      struct
      {
         CaseCondClause casecondclause_;
         CaseCondList   casecondlist_;
      } listCaseCondCons_;
   } u;
};

CaseCondList make_ListCaseCondEmpty( void );
CaseCondList make_ListCaseCondCons( CaseCondClause p0, CaseCondList p1 );

struct CaseCondClause_
{
   enum
   {
      is_CaseCondClauseItem
   } kind;
   union
   {
      struct
      {
         Expr     expr_;
         LineEol  lineeol_;
         StmtList stmtlist_;
      } caseCondClauseItem_;
   } u;
};

CaseCondClause make_CaseCondClauseItem( Expr p0, LineEol p1, StmtList p2 );

struct OtherwiseOpt_
{
   enum
   {
      is_OptOtherwiseEmpty,
      is_OptOtherwiseSome
   } kind;
   union
   {
      struct
      {
         LineEol  lineeol_;
         StmtList stmtlist_;
      } optOtherwiseSome_;
   } u;
};

OtherwiseOpt make_OptOtherwiseEmpty( void );
OtherwiseOpt make_OptOtherwiseSome( LineEol p0, StmtList p1 );

struct BreakExprOpt_
{
   enum
   {
      is_BreakExprOptEmpty,
      is_BreakExprOptSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } breakExprOptSome_;
   } u;
};

BreakExprOpt make_BreakExprOptEmpty( void );
BreakExprOpt make_BreakExprOptSome( Expr p0 );

struct RecoverOpt_
{
   enum
   {
      is_RecoverOptEmpty,
      is_RecoverOptSome
   } kind;
   union
   {
      struct
      {
         LineEol         lineeol_;
         RecoverUsingOpt recoverusingopt_;
         StmtList        stmtlist_;
      } recoverOptSome_;
   } u;
};

RecoverOpt make_RecoverOptEmpty( void );
RecoverOpt make_RecoverOptSome( RecoverUsingOpt p0, LineEol p1, StmtList p2 );

struct RecoverUsingOpt_
{
   enum
   {
      is_RecoverUsingOptEmpty,
      is_RecoverUsingOptSome
   } kind;
   union
   {
      struct
      {
         Ident ident_;
      } recoverUsingOptSome_;
   } u;
};

RecoverUsingOpt make_RecoverUsingOptEmpty( void );
RecoverUsingOpt make_RecoverUsingOptSome( Ident p0 );

struct EndSequence_
{
   enum
   {
      is_EndSequenceWord,
      is_EndSequenceClause
   } kind;
   union
   {
      struct
      {
         EndSequenceOpt endsequenceopt_;
      } endSequenceClause_;
   } u;
};

EndSequence make_EndSequenceWord( void );
EndSequence make_EndSequenceClause( EndSequenceOpt p0 );

struct EndSequenceOpt_
{
   enum
   {
      is_EndSequenceOptEmpty,
      is_EndSequenceOptSeq
   } kind;
   union
   {
   } u;
};

EndSequenceOpt make_EndSequenceOptEmpty( void );
EndSequenceOpt make_EndSequenceOptSeq( void );

struct SwitchCond_
{
   enum
   {
      is_SwitchCondExpr
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } switchCondExpr_;
   } u;
};

SwitchCond make_SwitchCondExpr( Expr p0 );

struct EndSwitch_
{
   enum
   {
      is_EndSwitchWord,
      is_EndSwitchClause
   } kind;
   union
   {
      struct
      {
         EndSwitchOpt endswitchopt_;
      } endSwitchClause_;
   } u;
};

EndSwitch make_EndSwitchWord( void );
EndSwitch make_EndSwitchClause( EndSwitchOpt p0 );

struct EndSwitchOpt_
{
   enum
   {
      is_EndSwitchOptEmpty,
      is_EndSwitchOptSwitch
   } kind;
   union
   {
   } u;
};

EndSwitchOpt make_EndSwitchOptEmpty( void );
EndSwitchOpt make_EndSwitchOptSwitch( void );

struct EndStruct_
{
   enum
   {
      is_EndStructWord,
      is_EndStructClause
   } kind;
   union
   {
      struct
      {
         EndStructOpt endstructopt_;
      } endStructClause_;
   } u;
};

EndStruct make_EndStructWord( void );
EndStruct make_EndStructClause( EndStructOpt p0 );

struct EndStructOpt_
{
   enum
   {
      is_EndStructOptEmpty,
      is_EndStructOptStruct
   } kind;
   union
   {
   } u;
};

EndStructOpt make_EndStructOptEmpty( void );
EndStructOpt make_EndStructOptStruct( void );

struct EndClass_
{
   enum
   {
      is_EndClassWord,
      is_EndClassClause
   } kind;
   union
   {
      struct
      {
         EndClassOpt endclassopt_;
      } endClassClause_;
   } u;
};

EndClass make_EndClassWord( void );
EndClass make_EndClassClause( EndClassOpt p0 );

struct EndClassOpt_
{
   enum
   {
      is_EndClassOptEmpty,
      is_EndClassOptClass
   } kind;
   union
   {
   } u;
};

EndClassOpt make_EndClassOptEmpty( void );
EndClassOpt make_EndClassOptClass( void );

struct EndEnum_
{
   enum
   {
      is_EndEnumWord,
      is_EndEnumClause
   } kind;
   union
   {
      struct
      {
         EndEnumOpt endenumopt_;
      } endEnumClause_;
   } u;
};

EndEnum make_EndEnumWord( void );
EndEnum make_EndEnumClause( EndEnumOpt p0 );

struct EndEnumOpt_
{
   enum
   {
      is_EndEnumOptEmpty,
      is_EndEnumOptEnum
   } kind;
   union
   {
   } u;
};

EndEnumOpt make_EndEnumOptEmpty( void );
EndEnumOpt make_EndEnumOptEnum( void );

struct CaseValue_
{
   enum
   {
      is_CaseValueInt,
      is_CaseValueStr
   } kind;
   union
   {
      struct
      {
         IntLit intlit_;
      } caseValueInt_;
      struct
      {
         Napis napis_;
      } caseValueStr_;
   } u;
};

CaseValue make_CaseValueInt( IntLit p0 );
CaseValue make_CaseValueStr( Napis p0 );

struct StmtEnd_
{
   enum
   {
      is_StmtEndLine
   } kind;
   union
   {
      struct
      {
         LineEol lineeol_;
      } stmtEndLine_;
   } u;
};

StmtEnd make_StmtEndLine( LineEol p0 );

struct EnumDecl_
{
   enum
   {
      is_EnumDeclNamed,
      is_EnumDeclAnon
   } kind;
   union
   {
      struct
      {
         EndEnum     endenum_;
         EnumListOpt enumlistopt_;
         Ident       ident_;
         LineEol     lineeol_;
         StmtEnd     stmtend_;
      } enumDeclNamed_;
      struct
      {
         EndEnum     endenum_;
         EnumListOpt enumlistopt_;
         LineEol     lineeol_;
         StmtEnd     stmtend_;
      } enumDeclAnon_;
   } u;
};

EnumDecl make_EnumDeclNamed( Ident p0, LineEol p1, EnumListOpt p2, EndEnum p3, StmtEnd p4 );
EnumDecl make_EnumDeclAnon( LineEol p0, EnumListOpt p1, EndEnum p2, StmtEnd p3 );

struct EnumListOpt_
{
   enum
   {
      is_OptEnumListEmpty,
      is_OptEnumListSome
   } kind;
   union
   {
      struct
      {
         EnumItem     enumitem_;
         EnumListTail enumlisttail_;
      } optEnumListSome_;
   } u;
};

EnumListOpt make_OptEnumListEmpty( void );
EnumListOpt make_OptEnumListSome( EnumItem p0, EnumListTail p1 );

struct EnumListTail_
{
   enum
   {
      is_ListEnumTailEmpty,
      is_ListEnumTailCons,
      is_ListEnumTailSep
   } kind;
   union
   {
      struct
      {
         EnumItem     enumitem_;
         EnumListTail enumlisttail_;
         EnumSep      enumsep_;
      } listEnumTailCons_;
      struct
      {
         EnumSep enumsep_;
      } listEnumTailSep_;
   } u;
};

EnumListTail make_ListEnumTailEmpty( void );
EnumListTail make_ListEnumTailCons( EnumSep p0, EnumItem p1, EnumListTail p2 );
EnumListTail make_ListEnumTailSep( EnumSep p0 );

struct EnumSep_
{
   enum
   {
      is_EnumSepComma,
      is_EnumSepLine
   } kind;
   union
   {
      struct
      {
         LineEolOpt lineeolopt_;
      } enumSepComma_;
      struct
      {
         LineEol lineeol_;
      } enumSepLine_;
   } u;
};

EnumSep make_EnumSepComma( LineEolOpt p0 );
EnumSep make_EnumSepLine( LineEol p0 );

struct EnumItem_
{
   enum
   {
      is_EnumItemDecl
   } kind;
   union
   {
      struct
      {
         EnumValueOpt enumvalueopt_;
         Ident        ident_;
      } enumItemDecl_;
   } u;
};

EnumItem make_EnumItemDecl( Ident p0, EnumValueOpt p1 );

struct EnumValueOpt_
{
   enum
   {
      is_OptEnumValueEmpty,
      is_OptEnumValueSome
   } kind;
   union
   {
      struct
      {
         IntLit intlit_;
      } optEnumValueSome_;
   } u;
};

EnumValueOpt make_OptEnumValueEmpty( void );
EnumValueOpt make_OptEnumValueSome( IntLit p0 );

struct LineEolOpt_
{
   enum
   {
      is_OptLineEolEmpty,
      is_OptLineEolSome
   } kind;
   union
   {
      struct
      {
         LineEol lineeol_;
      } optLineEolSome_;
   } u;
};

LineEolOpt make_OptLineEolEmpty( void );
LineEolOpt make_OptLineEolSome( LineEol p0 );

struct StructDecl_
{
   enum
   {
      is_StructDeclMain
   } kind;
   union
   {
      struct
      {
         EndStruct  endstruct_;
         Ident      ident_;
         LineEol    lineeol_;
         StmtEnd    stmtend_;
         StructBody structbody_;
      } structDeclMain_;
   } u;
};

StructDecl make_StructDeclMain( Ident p0, LineEol p1, StructBody p2, EndStruct p3, StmtEnd p4 );

struct StructBody_
{
   enum
   {
      is_StructBodyEmpty,
      is_StructBodyCons
   } kind;
   union
   {
      struct
      {
         StructBody   structbody_;
         StructMember structmember_;
      } structBodyCons_;
   } u;
};

StructBody make_StructBodyEmpty( void );
StructBody make_StructBodyCons( StructMember p0, StructBody p1 );

struct StructMember_
{
   enum
   {
      is_StructMemberVar
   } kind;
   union
   {
      struct
      {
         LineEol lineeol_;
         VarList varlist_;
      } structMemberVar_;
   } u;
};

StructMember make_StructMemberVar( VarList p0, LineEol p1 );

struct FieldInitList_
{
   enum
   {
      is_FieldInitListSingle,
      is_FieldInitListCons
   } kind;
   union
   {
      struct
      {
         FieldInit fieldinit_;
      } fieldInitListSingle_;
      struct
      {
         FieldInit     fieldinit_;
         FieldInitList fieldinitlist_;
      } fieldInitListCons_;
   } u;
};

FieldInitList make_FieldInitListSingle( FieldInit p0 );
FieldInitList make_FieldInitListCons( FieldInit p0, FieldInitList p1 );

struct FieldInit_
{
   enum
   {
      is_FieldInitItem
   } kind;
   union
   {
      struct
      {
         Expr  expr_;
         Ident ident_;
      } fieldInitItem_;
   } u;
};

FieldInit make_FieldInitItem( Ident p0, Expr p1 );

struct StaticDecl_
{
   enum
   {
      is_StaticStructDecl,
      is_StaticDeclItem
   } kind;
   union
   {
      struct
      {
         Ident         ident_;
         IdentInitList identinitlist_;
         StmtEnd       stmtend_;
      } staticStructDecl_;
      struct
      {
         StaticItemList staticitemlist_;
         StmtEnd        stmtend_;
      } staticDeclItem_;
   } u;
};

StaticDecl make_StaticStructDecl( Ident p0, IdentInitList p1, StmtEnd p2 );
StaticDecl make_StaticDeclItem( StaticItemList p0, StmtEnd p1 );

struct ClassDecl_
{
   enum
   {
      is_ClassDeclMain
   } kind;
   union
   {
      struct
      {
         ClassBody      classbody_;
         ClassName      classname_;
         CreateOpt      createopt_;
         EndClass       endclass_;
         InheritOpt     inheritopt_;
         LineEol        lineeol_;
         StaticClassOpt staticclassopt_;
         StmtEnd        stmtend_;
      } classDeclMain_;
   } u;
};

ClassDecl make_ClassDeclMain( CreateOpt p0, ClassName p1, InheritOpt p2, StaticClassOpt p3, LineEol p4, ClassBody p5,
                              EndClass p6, StmtEnd p7 );

struct CreateOpt_
{
   enum
   {
      is_OptCreateEmpty,
      is_OptCreateSome
   } kind;
   union
   {
   } u;
};

CreateOpt make_OptCreateEmpty( void );
CreateOpt make_OptCreateSome( void );

struct ClassName_
{
   enum
   {
      is_ClassNameIdent
   } kind;
   union
   {
      struct
      {
         Ident ident_;
      } classNameIdent_;
   } u;
};

ClassName make_ClassNameIdent( Ident p0 );

struct InheritOpt_
{
   enum
   {
      is_OptInheritEmpty,
      is_OptInheritSome
   } kind;
   union
   {
      struct
      {
         ClassName      classname_;
         InheritKeyword inheritkeyword_;
      } optInheritSome_;
   } u;
};

InheritOpt make_OptInheritEmpty( void );
InheritOpt make_OptInheritSome( InheritKeyword p0, ClassName p1 );

struct InheritKeyword_
{
   enum
   {
      is_InheritFrom,
      is_InheritInherit
   } kind;
   union
   {
   } u;
};

InheritKeyword make_InheritFrom( void );
InheritKeyword make_InheritInherit( void );

struct StaticClassOpt_
{
   enum
   {
      is_OptStaticClassEmpty,
      is_OptStaticClassSome
   } kind;
   union
   {
   } u;
};

StaticClassOpt make_OptStaticClassEmpty( void );
StaticClassOpt make_OptStaticClassSome( void );

struct ClassBody_
{
   enum
   {
      is_ClassBodyEmpty,
      is_ClassBodyCons
   } kind;
   union
   {
      struct
      {
         ClassBody   classbody_;
         ClassMember classmember_;
      } classBodyCons_;
   } u;
};

ClassBody make_ClassBodyEmpty( void );
ClassBody make_ClassBodyCons( ClassMember p0, ClassBody p1 );

struct ClassMember_
{
   enum
   {
      is_ClassMemberVisibility,
      is_ClassMemberVar,
      is_ClassMemberMethod
   } kind;
   union
   {
      struct
      {
         LineEol         lineeol_;
         VisibilityScope visibilityscope_;
      } classMemberVisibility_;
      struct
      {
         LineEol lineeol_;
         VarList varlist_;
      } classMemberVar_;
      struct
      {
         Ident           ident_;
         LineEol         lineeol_;
         MethodParamsOpt methodparamsopt_;
      } classMemberMethod_;
   } u;
};

ClassMember make_ClassMemberVisibility( VisibilityScope p0, LineEol p1 );
ClassMember make_ClassMemberVar( VarList p0, LineEol p1 );
ClassMember make_ClassMemberMethod( Ident p0, MethodParamsOpt p1, LineEol p2 );

struct VisibilityScope_
{
   enum
   {
      is_VisibilityExported,
      is_VisibilityVisible,
      is_VisibilityHidden,
      is_VisibilityProtected
   } kind;
   union
   {
   } u;
};

VisibilityScope make_VisibilityExported( void );
VisibilityScope make_VisibilityVisible( void );
VisibilityScope make_VisibilityHidden( void );
VisibilityScope make_VisibilityProtected( void );

struct VarList_
{
   enum
   {
      is_VarListSingle,
      is_VarListCons
   } kind;
   union
   {
      struct
      {
         VarDecl vardecl_;
      } varListSingle_;
      struct
      {
         VarDecl vardecl_;
         VarList varlist_;
      } varListCons_;
   } u;
};

VarList make_VarListSingle( VarDecl p0 );
VarList make_VarListCons( VarDecl p0, VarList p1 );

struct VarDecl_
{
   enum
   {
      is_VarDeclItem
   } kind;
   union
   {
      struct
      {
         Ident      ident_;
         VarInitOpt varinitopt_;
      } varDeclItem_;
   } u;
};

VarDecl make_VarDeclItem( Ident p0, VarInitOpt p1 );

struct VarInitOpt_
{
   enum
   {
      is_OptVarInitEmpty,
      is_OptVarInitSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } optVarInitSome_;
   } u;
};

VarInitOpt make_OptVarInitEmpty( void );
VarInitOpt make_OptVarInitSome( Expr p0 );

struct MethodParamsOpt_
{
   enum
   {
      is_MethodParamsEmpty,
      is_MethodParamsSome
   } kind;
   union
   {
      struct
      {
         ParamListOpt paramlistopt_;
      } methodParamsSome_;
   } u;
};

MethodParamsOpt make_MethodParamsEmpty( void );
MethodParamsOpt make_MethodParamsSome( ParamListOpt p0 );

struct Expr_
{
   enum
   {
      is_ExprAssignBase,
      is_ExprAndDot,
      is_ExprAndBase,
      is_ExprNotDot,
      is_ExprNotBase,
      is_ExprEq,
      is_ExprEq2,
      is_ExprNeq,
      is_ExprNeq2,
      is_ExprNeq3,
      is_ExprLt,
      is_ExprLe,
      is_ExprGt,
      is_ExprGe,
      is_ExprSubStr,
      is_ExprRelBase,
      is_ExprAdd,
      is_ExprSub,
      is_ExprAddBase,
      is_ExprMul,
      is_ExprDiv,
      is_ExprMod,
      is_ExprMulBase,
      is_ExprPow1,
      is_ExprPow2,
      is_ExprPowBase,
      is_ExprAddrOf,
      is_ExprDeref,
      is_ExprDecPre,
      is_ExprIncPre,
      is_ExprPlus,
      is_ExprMinus,
      is_ExprSignBase,
      is_ExprLit,
      is_ExprCall,
      is_ExprQId,
      is_ExprParen,
      is_ExprIndex,
      is_ExprArray,
      is_ExprBlock,
      is_ExprMethodCall,
      is_ExprFieldAccess,
      is_ExprStructInitNamed,
      is_ExprStructAnon,
      is_ExprDecPost,
      is_ExprIncPost
   } kind;
   union
   {
      struct
      {
         ExprOr expror_;
      } exprAssignBase_;
      struct
      {
         Expr expr_1, expr_2;
      } exprAndDot_;
      struct
      {
         Expr expr_;
      } exprAndBase_;
      struct
      {
         Expr expr_;
      } exprNotDot_;
      struct
      {
         Expr expr_;
      } exprNotBase_;
      struct
      {
         Expr expr_1, expr_2;
      } exprEq_;
      struct
      {
         Expr expr_1, expr_2;
      } exprEq2_;
      struct
      {
         Expr expr_1, expr_2;
      } exprNeq_;
      struct
      {
         Expr expr_1, expr_2;
      } exprNeq2_;
      struct
      {
         Expr expr_1, expr_2;
      } exprNeq3_;
      struct
      {
         Expr expr_1, expr_2;
      } exprLt_;
      struct
      {
         Expr expr_1, expr_2;
      } exprLe_;
      struct
      {
         Expr expr_1, expr_2;
      } exprGt_;
      struct
      {
         Expr expr_1, expr_2;
      } exprGe_;
      struct
      {
         Expr expr_1, expr_2;
      } exprSubStr_;
      struct
      {
         Expr expr_;
      } exprRelBase_;
      struct
      {
         Expr expr_1, expr_2;
      } exprAdd_;
      struct
      {
         Expr expr_1, expr_2;
      } exprSub_;
      struct
      {
         Expr expr_;
      } exprAddBase_;
      struct
      {
         Expr expr_1, expr_2;
      } exprMul_;
      struct
      {
         Expr expr_1, expr_2;
      } exprDiv_;
      struct
      {
         Expr expr_1, expr_2;
      } exprMod_;
      struct
      {
         Expr expr_;
      } exprMulBase_;
      struct
      {
         Expr expr_1, expr_2;
      } exprPow1_;
      struct
      {
         Expr expr_1, expr_2;
      } exprPow2_;
      struct
      {
         Expr expr_;
      } exprPowBase_;
      struct
      {
         LHS lhs_;
      } exprAddrOf_;
      struct
      {
         Expr expr_;
      } exprDeref_;
      struct
      {
         Expr expr_;
      } exprDecPre_;
      struct
      {
         Expr expr_;
      } exprIncPre_;
      struct
      {
         Expr expr_;
      } exprPlus_;
      struct
      {
         Expr expr_;
      } exprMinus_;
      struct
      {
         Expr expr_;
      } exprSignBase_;
      struct
      {
         Literal literal_;
      } exprLit_;
      struct
      {
         CallExpr callexpr_;
      } exprCall_;
      struct
      {
         QualifiedId qualifiedid_;
      } exprQId_;
      struct
      {
         Expr expr_;
      } exprParen_;
      struct
      {
         Expr          expr_;
         SubscriptList subscriptlist_;
      } exprIndex_;
      struct
      {
         ExprListOpt exprlistopt_;
      } exprArray_;
      struct
      {
         ExprListOpt  exprlistopt_;
         ParamListOpt paramlistopt_;
      } exprBlock_;
      struct
      {
         ArgListOpt arglistopt_;
         Expr       expr_;
         Ident      ident_;
      } exprMethodCall_;
      struct
      {
         Expr  expr_;
         Ident ident_;
      } exprFieldAccess_;
      struct
      {
         FieldInitList fieldinitlist_;
         QualifiedId   qualifiedid_;
      } exprStructInitNamed_;
      struct
      {
         FieldInitList fieldinitlist_;
      } exprStructAnon_;
      struct
      {
         Expr expr_;
      } exprDecPost_;
      struct
      {
         Expr expr_;
      } exprIncPost_;
   } u;
};

Expr make_ExprAssignBase( ExprOr p0 );
Expr make_ExprAndDot( Expr p0, Expr p1 );
Expr make_ExprAndBase( Expr p0 );
Expr make_ExprNotDot( Expr p0 );
Expr make_ExprNotBase( Expr p0 );
Expr make_ExprEq( Expr p0, Expr p1 );
Expr make_ExprEq2( Expr p0, Expr p1 );
Expr make_ExprNeq( Expr p0, Expr p1 );
Expr make_ExprNeq2( Expr p0, Expr p1 );
Expr make_ExprNeq3( Expr p0, Expr p1 );
Expr make_ExprLt( Expr p0, Expr p1 );
Expr make_ExprLe( Expr p0, Expr p1 );
Expr make_ExprGt( Expr p0, Expr p1 );
Expr make_ExprGe( Expr p0, Expr p1 );
Expr make_ExprSubStr( Expr p0, Expr p1 );
Expr make_ExprRelBase( Expr p0 );
Expr make_ExprAdd( Expr p0, Expr p1 );
Expr make_ExprSub( Expr p0, Expr p1 );
Expr make_ExprAddBase( Expr p0 );
Expr make_ExprMul( Expr p0, Expr p1 );
Expr make_ExprDiv( Expr p0, Expr p1 );
Expr make_ExprMod( Expr p0, Expr p1 );
Expr make_ExprMulBase( Expr p0 );
Expr make_ExprPow1( Expr p0, Expr p1 );
Expr make_ExprPow2( Expr p0, Expr p1 );
Expr make_ExprPowBase( Expr p0 );
Expr make_ExprAddrOf( LHS p0 );
Expr make_ExprDeref( Expr p0 );
Expr make_ExprDecPre( Expr p0 );
Expr make_ExprIncPre( Expr p0 );
Expr make_ExprPlus( Expr p0 );
Expr make_ExprMinus( Expr p0 );
Expr make_ExprSignBase( Expr p0 );
Expr make_ExprLit( Literal p0 );
Expr make_ExprCall( CallExpr p0 );
Expr make_ExprQId( QualifiedId p0 );
Expr make_ExprParen( Expr p0 );
Expr make_ExprIndex( Expr p0, SubscriptList p1 );
Expr make_ExprArray( ExprListOpt p0 );
Expr make_ExprBlock( ParamListOpt p0, ExprListOpt p1 );
Expr make_ExprMethodCall( Expr p0, Ident p1, ArgListOpt p2 );
Expr make_ExprFieldAccess( Expr p0, Ident p1 );
Expr make_ExprStructInitNamed( QualifiedId p0, FieldInitList p1 );
Expr make_ExprStructAnon( FieldInitList p0 );
Expr make_ExprDecPost( Expr p0 );
Expr make_ExprIncPost( Expr p0 );

struct ExprOr_
{
   enum
   {
      is_ExprOrDot,
      is_ExprOrBase
   } kind;
   union
   {
      struct
      {
         Expr   expr_;
         ExprOr expror_;
      } exprOrDot_;
      struct
      {
         Expr expr_;
      } exprOrBase_;
   } u;
};

ExprOr make_ExprOrDot( ExprOr p0, Expr p1 );
ExprOr make_ExprOrBase( Expr p0 );

struct CallExpr_
{
   enum
   {
      is_CallExprMain
   } kind;
   union
   {
      struct
      {
         ArgListOpt  arglistopt_;
         QualifiedId qualifiedid_;
      } callExprMain_;
   } u;
};

CallExpr make_CallExprMain( QualifiedId p0, ArgListOpt p1 );

struct ArgListOpt_
{
   enum
   {
      is_OptArgListEmpty,
      is_OptArgListSome
   } kind;
   union
   {
      struct
      {
         ArgListTail arglisttail_;
         Expr        expr_;
      } optArgListSome_;
   } u;
};

ArgListOpt make_OptArgListEmpty( void );
ArgListOpt make_OptArgListSome( Expr p0, ArgListTail p1 );

struct ArgListTail_
{
   enum
   {
      is_ListArgTailEmpty,
      is_ListArgTailCons
   } kind;
   union
   {
      struct
      {
         ArgListTail arglisttail_;
         Expr        expr_;
      } listArgTailCons_;
   } u;
};

ArgListTail make_ListArgTailEmpty( void );
ArgListTail make_ListArgTailCons( Expr p0, ArgListTail p1 );

struct ExprListOpt_
{
   enum
   {
      is_OptExprListEmpty,
      is_OptExprListSome
   } kind;
   union
   {
      struct
      {
         Expr         expr_;
         ExprListTail exprlisttail_;
      } optExprListSome_;
   } u;
};

ExprListOpt make_OptExprListEmpty( void );
ExprListOpt make_OptExprListSome( Expr p0, ExprListTail p1 );

struct ExprListTail_
{
   enum
   {
      is_ListExprTailEmpty,
      is_ListExprTailCons
   } kind;
   union
   {
      struct
      {
         Expr         expr_;
         ExprListTail exprlisttail_;
      } listExprTailCons_;
   } u;
};

ExprListTail make_ListExprTailEmpty( void );
ExprListTail make_ListExprTailCons( Expr p0, ExprListTail p1 );

struct QualifiedId_
{
   enum
   {
      is_QualifiedIdSingle,
      is_QualifiedIdMore
   } kind;
   union
   {
      struct
      {
         Ident ident_;
      } qualifiedIdSingle_;
      struct
      {
         Ident       ident_;
         QualifiedId qualifiedid_;
      } qualifiedIdMore_;
   } u;
};

QualifiedId make_QualifiedIdSingle( Ident p0 );
QualifiedId make_QualifiedIdMore( Ident p0, QualifiedId p1 );

struct LHS_
{
   enum
   {
      is_LHSVal,
      is_LHSDeref
   } kind;
   union
   {
      struct
      {
         LValue lvalue_;
      } lHSVal_;
      struct
      {
         Expr expr_;
      } lHSDeref_;
   } u;
};

LHS make_LHSVal( LValue p0 );
LHS make_LHSDeref( Expr p0 );

struct LValue_
{
   enum
   {
      is_LValQId,
      is_LValField,
      is_LValIndex
   } kind;
   union
   {
      struct
      {
         QualifiedId qualifiedid_;
      } lValQId_;
      struct
      {
         Ident  ident_;
         LValue lvalue_;
      } lValField_;
      struct
      {
         LValue        lvalue_;
         SubscriptList subscriptlist_;
      } lValIndex_;
   } u;
};

LValue make_LValQId( QualifiedId p0 );
LValue make_LValField( LValue p0, Ident p1 );
LValue make_LValIndex( LValue p0, SubscriptList p1 );

struct SubscriptList_
{
   enum
   {
      is_SubscriptListSingle
   } kind;
   union
   {
      struct
      {
         Expr              expr_;
         SubscriptListTail subscriptlisttail_;
      } subscriptListSingle_;
   } u;
};

SubscriptList make_SubscriptListSingle( Expr p0, SubscriptListTail p1 );

struct SubscriptListTail_
{
   enum
   {
      is_ListSubscriptTailEmpty,
      is_ListSubscriptTailCons
   } kind;
   union
   {
      struct
      {
         Expr              expr_;
         SubscriptListTail subscriptlisttail_;
      } listSubscriptTailCons_;
   } u;
};

SubscriptListTail make_ListSubscriptTailEmpty( void );
SubscriptListTail make_ListSubscriptTailCons( Expr p0, SubscriptListTail p1 );

struct Literal_
{
   enum
   {
      is_LitNil,
      is_LitTrueDot,
      is_LitFalseDot,
      is_LitInt,
      is_LitFloat,
      is_LitStr
   } kind;
   union
   {
      struct
      {
         IntLit intlit_;
      } litInt_;
      struct
      {
         FloatLit floatlit_;
      } litFloat_;
      struct
      {
         Napis napis_;
      } litStr_;
   } u;
};

Literal make_LitNil( void );
Literal make_LitTrueDot( void );
Literal make_LitFalseDot( void );
Literal make_LitInt( IntLit p0 );
Literal make_LitFloat( FloatLit p0 );
Literal make_LitStr( Napis p0 );

struct Napis_
{
   enum
   {
      is_NapisStr
   } kind;
   union
   {
      struct
      {
         StrLit strlit_;
      } napisStr_;
   } u;
};

Napis make_NapisStr( StrLit p0 );

struct Def_
{
   enum
   {
      is_DefFun,
      is_DefProc,
      is_DefMeth
   } kind;
   union
   {
      struct
      {
         FunctionDef functiondef_;
      } defFun_;
      struct
      {
         ProcedureDef proceduredef_;
      } defProc_;
      struct
      {
         MethodDef methoddef_;
      } defMeth_;
   } u;
};

Def make_DefFun( FunctionDef p0 );
Def make_DefProc( ProcedureDef p0 );
Def make_DefMeth( MethodDef p0 );

struct FunctionDef_
{
   enum
   {
      is_FunctionDefMain
   } kind;
   union
   {
      struct
      {
         Ident            ident_;
         LineEol          lineeol_;
         LocalDeclsOpt    localdeclsopt_;
         ParamListOpt     paramlistopt_;
         StaticDeclsOpt   staticdeclsopt_;
         StaticOpt        staticopt_;
         StmtListNonEmpty stmtlistnonempty_;
      } functionDefMain_;
   } u;
};

FunctionDef make_FunctionDefMain( StaticOpt p0, Ident p1, ParamListOpt p2, LineEol p3, LocalDeclsOpt p4,
                                  StaticDeclsOpt p5, StmtListNonEmpty p6 );

struct ProcedureDef_
{
   enum
   {
      is_ProcedureDefMain
   } kind;
   union
   {
      struct
      {
         Ident            ident_;
         LineEol          lineeol_;
         LocalDeclsOpt    localdeclsopt_;
         ParamListOpt     paramlistopt_;
         StaticDeclsOpt   staticdeclsopt_;
         StaticOpt        staticopt_;
         StmtListNonEmpty stmtlistnonempty_;
      } procedureDefMain_;
   } u;
};

ProcedureDef make_ProcedureDefMain( StaticOpt p0, Ident p1, ParamListOpt p2, LineEol p3, LocalDeclsOpt p4,
                                    StaticDeclsOpt p5, StmtListNonEmpty p6 );

struct StaticOpt_
{
   enum
   {
      is_OptStaticEmpty,
      is_OptStaticSome
   } kind;
   union
   {
   } u;
};

StaticOpt make_OptStaticEmpty( void );
StaticOpt make_OptStaticSome( void );

struct LocalDeclsOpt_
{
   enum
   {
      is_ListLocalDeclEmpty,
      is_ListLocalDeclLine,
      is_ListLocalDeclCons
   } kind;
   union
   {
      struct
      {
         LineEol       lineeol_;
         LocalDeclsOpt localdeclsopt_;
      } listLocalDeclLine_;
      struct
      {
         LocalDecl     localdecl_;
         LocalDeclsOpt localdeclsopt_;
      } listLocalDeclCons_;
   } u;
};

LocalDeclsOpt make_ListLocalDeclEmpty( void );
LocalDeclsOpt make_ListLocalDeclLine( LineEol p0, LocalDeclsOpt p1 );
LocalDeclsOpt make_ListLocalDeclCons( LocalDecl p0, LocalDeclsOpt p1 );

struct LocalDecl_
{
   enum
   {
      is_LocalDeclItem
   } kind;
   union
   {
      struct
      {
         IdentInitList identinitlist_;
         StmtEnd       stmtend_;
      } localDeclItem_;
   } u;
};

LocalDecl make_LocalDeclItem( IdentInitList p0, StmtEnd p1 );

struct StaticDeclsOpt_
{
   enum
   {
      is_ListStaticDeclEmpty,
      is_ListStaticDeclCons
   } kind;
   union
   {
      struct
      {
         StaticDecl     staticdecl_;
         StaticDeclsOpt staticdeclsopt_;
      } listStaticDeclCons_;
   } u;
};

StaticDeclsOpt make_ListStaticDeclEmpty( void );
StaticDeclsOpt make_ListStaticDeclCons( StaticDecl p0, StaticDeclsOpt p1 );

struct StaticItemList_
{
   enum
   {
      is_StaticItemListSingle
   } kind;
   union
   {
      struct
      {
         StaticItem     staticitem_;
         StaticItemTail staticitemtail_;
      } staticItemListSingle_;
   } u;
};

StaticItemList make_StaticItemListSingle( StaticItem p0, StaticItemTail p1 );

struct StaticItemTail_
{
   enum
   {
      is_StaticItemTailEmpty,
      is_StaticItemTailCons
   } kind;
   union
   {
      struct
      {
         StaticItem     staticitem_;
         StaticItemTail staticitemtail_;
      } staticItemTailCons_;
   } u;
};

StaticItemTail make_StaticItemTailEmpty( void );
StaticItemTail make_StaticItemTailCons( StaticItem p0, StaticItemTail p1 );

struct StaticItem_
{
   enum
   {
      is_StaticItemMain
   } kind;
   union
   {
      struct
      {
         Ident              ident_;
         StaticArrayDimsOpt staticarraydimsopt_;
         StaticInitOpt      staticinitopt_;
      } staticItemMain_;
   } u;
};

StaticItem make_StaticItemMain( Ident p0, StaticArrayDimsOpt p1, StaticInitOpt p2 );

struct StaticArrayDimsOpt_
{
   enum
   {
      is_StaticArrayDimsEmpty,
      is_StaticArrayDimsCons
   } kind;
   union
   {
      struct
      {
         StaticArrayDimsOpt staticarraydimsopt_;
         SubscriptList      subscriptlist_;
      } staticArrayDimsCons_;
   } u;
};

StaticArrayDimsOpt make_StaticArrayDimsEmpty( void );
StaticArrayDimsOpt make_StaticArrayDimsCons( SubscriptList p0, StaticArrayDimsOpt p1 );

struct StaticInitOpt_
{
   enum
   {
      is_StaticInitEmpty,
      is_StaticInitSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } staticInitSome_;
   } u;
};

StaticInitOpt make_StaticInitEmpty( void );
StaticInitOpt make_StaticInitSome( Expr p0 );

struct IdentInitList_
{
   enum
   {
      is_ListIdentInitSingle
   } kind;
   union
   {
      struct
      {
         IdentInit     identinit_;
         IdentInitTail identinittail_;
      } listIdentInitSingle_;
   } u;
};

IdentInitList make_ListIdentInitSingle( IdentInit p0, IdentInitTail p1 );

struct IdentInitTail_
{
   enum
   {
      is_ListIdentInitTailEmpty,
      is_ListIdentInitTailCons
   } kind;
   union
   {
      struct
      {
         IdentInit     identinit_;
         IdentInitTail identinittail_;
      } listIdentInitTailCons_;
   } u;
};

IdentInitTail make_ListIdentInitTailEmpty( void );
IdentInitTail make_ListIdentInitTailCons( IdentInit p0, IdentInitTail p1 );

struct IdentInit_
{
   enum
   {
      is_IdentInitItem
   } kind;
   union
   {
      struct
      {
         Ident   ident_;
         InitOpt initopt_;
      } identInitItem_;
   } u;
};

IdentInit make_IdentInitItem( Ident p0, InitOpt p1 );

struct InitOpt_
{
   enum
   {
      is_OptInitEmpty,
      is_OptInitSome
   } kind;
   union
   {
      struct
      {
         Expr expr_;
      } optInitSome_;
   } u;
};

InitOpt make_OptInitEmpty( void );
InitOpt make_OptInitSome( Expr p0 );

struct MethodDef_
{
   enum
   {
      is_MethodDefMain
   } kind;
   union
   {
      struct
      {
         ClassName        classname_;
         Ident            ident_;
         LineEol          lineeol_;
         LocalDeclsOpt    localdeclsopt_;
         ParamListOpt     paramlistopt_;
         StaticDeclsOpt   staticdeclsopt_;
         StaticOpt        staticopt_;
         StmtListNonEmpty stmtlistnonempty_;
      } methodDefMain_;
   } u;
};

MethodDef make_MethodDefMain( StaticOpt p0, Ident p1, ParamListOpt p2, ClassName p3, LineEol p4, LocalDeclsOpt p5,
                              StaticDeclsOpt p6, StmtListNonEmpty p7 );

/***************************   Cloning   ******************************/

Program            clone_Program( Program p );
LeadingEols        clone_LeadingEols( LeadingEols p );
TopDecls           clone_TopDecls( TopDecls p );
TopDecl            clone_TopDecl( TopDecl p );
Defs               clone_Defs( Defs p );
PreprocDecl        clone_PreprocDecl( PreprocDecl p );
ParamListOpt       clone_ParamListOpt( ParamListOpt p );
ParamListTail      clone_ParamListTail( ParamListTail p );
Stmt               clone_Stmt( Stmt p );
ReturnExprOpt      clone_ReturnExprOpt( ReturnExprOpt p );
StmtList           clone_StmtList( StmtList p );
StmtListNonEmpty   clone_StmtListNonEmpty( StmtListNonEmpty p );
ElseIfList         clone_ElseIfList( ElseIfList p );
ElseIf             clone_ElseIf( ElseIf p );
ElseOpt            clone_ElseOpt( ElseOpt p );
IfCond             clone_IfCond( IfCond p );
EndIf              clone_EndIf( EndIf p );
EndIfOpt           clone_EndIfOpt( EndIfOpt p );
DoOpt              clone_DoOpt( DoOpt p );
WhileCond          clone_WhileCond( WhileCond p );
EndDo              clone_EndDo( EndDo p );
EndDoOpt           clone_EndDoOpt( EndDoOpt p );
EndCase            clone_EndCase( EndCase p );
EndCaseOpt         clone_EndCaseOpt( EndCaseOpt p );
StepOpt            clone_StepOpt( StepOpt p );
EndFor             clone_EndFor( EndFor p );
EndForOpt          clone_EndForOpt( EndForOpt p );
ForEachVars        clone_ForEachVars( ForEachVars p );
ForEachVarsTail    clone_ForEachVarsTail( ForEachVarsTail p );
ForEachExprs       clone_ForEachExprs( ForEachExprs p );
ForEachExprsTail   clone_ForEachExprsTail( ForEachExprsTail p );
ForEachDescOpt     clone_ForEachDescOpt( ForEachDescOpt p );
CaseList           clone_CaseList( CaseList p );
CaseClause         clone_CaseClause( CaseClause p );
CaseCondList       clone_CaseCondList( CaseCondList p );
CaseCondClause     clone_CaseCondClause( CaseCondClause p );
OtherwiseOpt       clone_OtherwiseOpt( OtherwiseOpt p );
BreakExprOpt       clone_BreakExprOpt( BreakExprOpt p );
RecoverOpt         clone_RecoverOpt( RecoverOpt p );
RecoverUsingOpt    clone_RecoverUsingOpt( RecoverUsingOpt p );
EndSequence        clone_EndSequence( EndSequence p );
EndSequenceOpt     clone_EndSequenceOpt( EndSequenceOpt p );
SwitchCond         clone_SwitchCond( SwitchCond p );
EndSwitch          clone_EndSwitch( EndSwitch p );
EndSwitchOpt       clone_EndSwitchOpt( EndSwitchOpt p );
EndStruct          clone_EndStruct( EndStruct p );
EndStructOpt       clone_EndStructOpt( EndStructOpt p );
EndClass           clone_EndClass( EndClass p );
EndClassOpt        clone_EndClassOpt( EndClassOpt p );
EndEnum            clone_EndEnum( EndEnum p );
EndEnumOpt         clone_EndEnumOpt( EndEnumOpt p );
CaseValue          clone_CaseValue( CaseValue p );
StmtEnd            clone_StmtEnd( StmtEnd p );
EnumDecl           clone_EnumDecl( EnumDecl p );
EnumListOpt        clone_EnumListOpt( EnumListOpt p );
EnumListTail       clone_EnumListTail( EnumListTail p );
EnumSep            clone_EnumSep( EnumSep p );
EnumItem           clone_EnumItem( EnumItem p );
EnumValueOpt       clone_EnumValueOpt( EnumValueOpt p );
LineEolOpt         clone_LineEolOpt( LineEolOpt p );
StructDecl         clone_StructDecl( StructDecl p );
StructBody         clone_StructBody( StructBody p );
StructMember       clone_StructMember( StructMember p );
FieldInitList      clone_FieldInitList( FieldInitList p );
FieldInit          clone_FieldInit( FieldInit p );
StaticDecl         clone_StaticDecl( StaticDecl p );
ClassDecl          clone_ClassDecl( ClassDecl p );
CreateOpt          clone_CreateOpt( CreateOpt p );
ClassName          clone_ClassName( ClassName p );
InheritOpt         clone_InheritOpt( InheritOpt p );
InheritKeyword     clone_InheritKeyword( InheritKeyword p );
StaticClassOpt     clone_StaticClassOpt( StaticClassOpt p );
ClassBody          clone_ClassBody( ClassBody p );
ClassMember        clone_ClassMember( ClassMember p );
VisibilityScope    clone_VisibilityScope( VisibilityScope p );
VarList            clone_VarList( VarList p );
VarDecl            clone_VarDecl( VarDecl p );
VarInitOpt         clone_VarInitOpt( VarInitOpt p );
MethodParamsOpt    clone_MethodParamsOpt( MethodParamsOpt p );
Expr               clone_Expr( Expr p );
ExprOr             clone_ExprOr( ExprOr p );
CallExpr           clone_CallExpr( CallExpr p );
ArgListOpt         clone_ArgListOpt( ArgListOpt p );
ArgListTail        clone_ArgListTail( ArgListTail p );
ExprListOpt        clone_ExprListOpt( ExprListOpt p );
ExprListTail       clone_ExprListTail( ExprListTail p );
QualifiedId        clone_QualifiedId( QualifiedId p );
LHS                clone_LHS( LHS p );
LValue             clone_LValue( LValue p );
SubscriptList      clone_SubscriptList( SubscriptList p );
SubscriptListTail  clone_SubscriptListTail( SubscriptListTail p );
Literal            clone_Literal( Literal p );
Napis              clone_Napis( Napis p );
Def                clone_Def( Def p );
FunctionDef        clone_FunctionDef( FunctionDef p );
ProcedureDef       clone_ProcedureDef( ProcedureDef p );
StaticOpt          clone_StaticOpt( StaticOpt p );
LocalDeclsOpt      clone_LocalDeclsOpt( LocalDeclsOpt p );
LocalDecl          clone_LocalDecl( LocalDecl p );
StaticDeclsOpt     clone_StaticDeclsOpt( StaticDeclsOpt p );
StaticItemList     clone_StaticItemList( StaticItemList p );
StaticItemTail     clone_StaticItemTail( StaticItemTail p );
StaticItem         clone_StaticItem( StaticItem p );
StaticArrayDimsOpt clone_StaticArrayDimsOpt( StaticArrayDimsOpt p );
StaticInitOpt      clone_StaticInitOpt( StaticInitOpt p );
IdentInitList      clone_IdentInitList( IdentInitList p );
IdentInitTail      clone_IdentInitTail( IdentInitTail p );
IdentInit          clone_IdentInit( IdentInit p );
InitOpt            clone_InitOpt( InitOpt p );
MethodDef          clone_MethodDef( MethodDef p );

/********************   Recursive Destructors    **********************/

/* These free an entire abstract syntax tree
 * including all subtrees and strings.
 *
 * Will not work properly if there is sharing in the tree,
 * i.e., when some pointers are aliased.  In this case
 * it will attempt to free the same memory twice.
 */

void free_Program( Program p );
void free_LeadingEols( LeadingEols p );
void free_TopDecls( TopDecls p );
void free_TopDecl( TopDecl p );
void free_Defs( Defs p );
void free_PreprocDecl( PreprocDecl p );
void free_ParamListOpt( ParamListOpt p );
void free_ParamListTail( ParamListTail p );
void free_Stmt( Stmt p );
void free_ReturnExprOpt( ReturnExprOpt p );
void free_StmtList( StmtList p );
void free_StmtListNonEmpty( StmtListNonEmpty p );
void free_ElseIfList( ElseIfList p );
void free_ElseIf( ElseIf p );
void free_ElseOpt( ElseOpt p );
void free_IfCond( IfCond p );
void free_EndIf( EndIf p );
void free_EndIfOpt( EndIfOpt p );
void free_DoOpt( DoOpt p );
void free_WhileCond( WhileCond p );
void free_EndDo( EndDo p );
void free_EndDoOpt( EndDoOpt p );
void free_EndCase( EndCase p );
void free_EndCaseOpt( EndCaseOpt p );
void free_StepOpt( StepOpt p );
void free_EndFor( EndFor p );
void free_EndForOpt( EndForOpt p );
void free_ForEachVars( ForEachVars p );
void free_ForEachVarsTail( ForEachVarsTail p );
void free_ForEachExprs( ForEachExprs p );
void free_ForEachExprsTail( ForEachExprsTail p );
void free_ForEachDescOpt( ForEachDescOpt p );
void free_CaseList( CaseList p );
void free_CaseClause( CaseClause p );
void free_CaseCondList( CaseCondList p );
void free_CaseCondClause( CaseCondClause p );
void free_OtherwiseOpt( OtherwiseOpt p );
void free_BreakExprOpt( BreakExprOpt p );
void free_RecoverOpt( RecoverOpt p );
void free_RecoverUsingOpt( RecoverUsingOpt p );
void free_EndSequence( EndSequence p );
void free_EndSequenceOpt( EndSequenceOpt p );
void free_SwitchCond( SwitchCond p );
void free_EndSwitch( EndSwitch p );
void free_EndSwitchOpt( EndSwitchOpt p );
void free_EndStruct( EndStruct p );
void free_EndStructOpt( EndStructOpt p );
void free_EndClass( EndClass p );
void free_EndClassOpt( EndClassOpt p );
void free_EndEnum( EndEnum p );
void free_EndEnumOpt( EndEnumOpt p );
void free_CaseValue( CaseValue p );
void free_StmtEnd( StmtEnd p );
void free_EnumDecl( EnumDecl p );
void free_EnumListOpt( EnumListOpt p );
void free_EnumListTail( EnumListTail p );
void free_EnumSep( EnumSep p );
void free_EnumItem( EnumItem p );
void free_EnumValueOpt( EnumValueOpt p );
void free_LineEolOpt( LineEolOpt p );
void free_StructDecl( StructDecl p );
void free_StructBody( StructBody p );
void free_StructMember( StructMember p );
void free_FieldInitList( FieldInitList p );
void free_FieldInit( FieldInit p );
void free_StaticDecl( StaticDecl p );
void free_ClassDecl( ClassDecl p );
void free_CreateOpt( CreateOpt p );
void free_ClassName( ClassName p );
void free_InheritOpt( InheritOpt p );
void free_InheritKeyword( InheritKeyword p );
void free_StaticClassOpt( StaticClassOpt p );
void free_ClassBody( ClassBody p );
void free_ClassMember( ClassMember p );
void free_VisibilityScope( VisibilityScope p );
void free_VarList( VarList p );
void free_VarDecl( VarDecl p );
void free_VarInitOpt( VarInitOpt p );
void free_MethodParamsOpt( MethodParamsOpt p );
void free_Expr( Expr p );
void free_ExprOr( ExprOr p );
void free_CallExpr( CallExpr p );
void free_ArgListOpt( ArgListOpt p );
void free_ArgListTail( ArgListTail p );
void free_ExprListOpt( ExprListOpt p );
void free_ExprListTail( ExprListTail p );
void free_QualifiedId( QualifiedId p );
void free_LHS( LHS p );
void free_LValue( LValue p );
void free_SubscriptList( SubscriptList p );
void free_SubscriptListTail( SubscriptListTail p );
void free_Literal( Literal p );
void free_Napis( Napis p );
void free_Def( Def p );
void free_FunctionDef( FunctionDef p );
void free_ProcedureDef( ProcedureDef p );
void free_StaticOpt( StaticOpt p );
void free_LocalDeclsOpt( LocalDeclsOpt p );
void free_LocalDecl( LocalDecl p );
void free_StaticDeclsOpt( StaticDeclsOpt p );
void free_StaticItemList( StaticItemList p );
void free_StaticItemTail( StaticItemTail p );
void free_StaticItem( StaticItem p );
void free_StaticArrayDimsOpt( StaticArrayDimsOpt p );
void free_StaticInitOpt( StaticInitOpt p );
void free_IdentInitList( IdentInitList p );
void free_IdentInitTail( IdentInitTail p );
void free_IdentInit( IdentInit p );
void free_InitOpt( InitOpt p );
void free_MethodDef( MethodDef p );

#endif
