/* File generated by the BNF Converter (bnfc 2.9.6.1). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include "Absyn.h"
#include <stdio.h>

Program pProgram( FILE *inp );
Program psProgram( const char *str );

#endif
